spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rpan
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379
#      sentinel:
#        username: root
#        password: root

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#
com:
  zzw:
    pan:
      canal:
        canal-server-ip: 127.0.0.1
        canal-server-port: 9933
        user-name: admin
        password: admin
        destination: test



