spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rpan
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    servlet:
      load-on-startup: 1

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


